local ch = KSG_CONF.IS_CH
local RUNES = ch and "符文" or "Runes"


STRINGS.NAMES.KSG_POWER_HUNGER = ch and "食神的试炼" or "Chef's Trial"
STRINGS.NAMES.KSG_POWER_SANITY = ch and "先知的试炼" or "Prophet's Trial"
STRINGS.NAMES.KSG_POWER_HEALTH = ch and "战神的试炼" or "Mars's Trial"
STRINGS.NAMES.KSG_POWER_PICKER = ch and "仙子的试炼" or "Fairy's Trial"
STRINGS.NAMES.KSG_POWER_FARMER = ch and "神农的试炼" or "Farmer's Trial"
STRINGS.NAMES.KSG_POWER_HUNTER = ch and "猎神的试炼" or "Hunter's Trial"


STRINGS.NAMES.KSG_POWER_DAMAGE = ch and "锋锐" or "Sharp"
STRINGS.NAMES.KSG_POWER_SPEEDR = ch and "迅捷" or "Speed"
STRINGS.NAMES.KSG_POWER_AOEATK = ch and "群伤" or "Aoe Atk"
STRINGS.NAMES.KSG_POWER_MAXUSE = ch and "耐久" or "Durable"
STRINGS.NAMES.KSG_POWER_BLOODR = ch and "吸血" or "Vampire"
STRINGS.NAMES.KSG_POWER_CHOPER = ch and "伐木" or "Chop"
STRINGS.NAMES.KSG_POWER_MINEER = ch and "耐久" or "Mine"
STRINGS.NAMES.KSG_POWER_WATERR = ch and "防水" or "Water Proof"
STRINGS.NAMES.KSG_POWER_TMPRET = ch and "保温" or "Insulation"
STRINGS.NAMES.KSG_POWER_DAPNER = ch and "愉悦" or "Happy"
STRINGS.NAMES.KSG_POWER_ABSORB = ch and "防御" or "Absorb"
STRINGS.NAMES.KSG_RUNES_DAMAGE = STRINGS.NAMES.KSG_POWER_DAMAGE..RUNES
STRINGS.NAMES.KSG_RUNES_SPEEDR = STRINGS.NAMES.KSG_POWER_SPEEDR..RUNES
STRINGS.NAMES.KSG_RUNES_AOEATK = STRINGS.NAMES.KSG_POWER_AOEATK..RUNES
STRINGS.NAMES.KSG_RUNES_MAXUSE = STRINGS.NAMES.KSG_POWER_MAXUSE..RUNES
STRINGS.NAMES.KSG_RUNES_BLOODR = STRINGS.NAMES.KSG_POWER_BLOODR..RUNES
STRINGS.NAMES.KSG_RUNES_CHOPER = STRINGS.NAMES.KSG_POWER_CHOPER..RUNES
STRINGS.NAMES.KSG_RUNES_MINEER = STRINGS.NAMES.KSG_POWER_MINEER..RUNES
STRINGS.NAMES.KSG_RUNES_WATERR = STRINGS.NAMES.KSG_POWER_WATERR..RUNES
STRINGS.NAMES.KSG_RUNES_TMPRET = STRINGS.NAMES.KSG_POWER_TMPRET..RUNES
STRINGS.NAMES.KSG_RUNES_DAPNER = STRINGS.NAMES.KSG_POWER_DAPNER..RUNES
STRINGS.NAMES.KSG_RUNES_ABSORB = STRINGS.NAMES.KSG_POWER_ABSORB..RUNES


STRINGS.NAMES.KSG_POWER_MON_HEALTH = ch and "生命" or "Health"
STRINGS.NAMES.KSG_POWER_MON_SPEEDR = ch and "迅捷" or "Speed"
STRINGS.NAMES.KSG_POWER_MON_CRTATK = ch and "暴击" or "Critical Atk"
STRINGS.NAMES.KSG_POWER_MON_DAMAGE = ch and "增伤" or "Damage"
STRINGS.NAMES.KSG_POWER_MON_RELATK = ch and "真伤" or "Real Damage"
STRINGS.NAMES.KSG_POWER_MON_ICEEPL = ch and "冰爆" or "Ice Explosion"
STRINGS.NAMES.KSG_POWER_MON_SANAUR = ch and "恐惧" or "Fear"
STRINGS.NAMES.KSG_POWER_MON_ABSORB = ch and "防御" or "Absorb"
STRINGS.NAMES.KSG_POWER_MON_KNOCKR = ch and "击飞" or "Knock"
STRINGS.NAMES.KSG_POWER_MON_STEALR = ch and "窃取" or "Steal"
STRINGS.NAMES.KSG_POWER_MON_BLOODR = ch and "吸血" or "Vampire"
STRINGS.NAMES.KSG_POWER_MON_THORNR = ch and "荆棘" or "Thorns"



STRINGS.KSG_POWER_NOTICE = {}
STRINGS.KSG_POWER_NOTICE.GAIN    = ch and "%s获得了%s" or "%s gained %s "
STRINGS.KSG_POWER_NOTICE.UPGRADE = ch and "%s等级提升" or "%s level up"







