

local EQUIPS = UGPOWERS.EQUIPS

local POWER_RARITY = {
    [EQUIPS.ABSORB] = UGRARITY.GREEN,
    [EQUIPS.BLINDR] = UGRARITY.BLUE ,
    [EQUIPS.CHOPER] = UGRARITY.WHITE,
    [EQUIPS.CRITER] = UGRARITY.PURPLE,
    [EQUIPS.DAMAGE] = UGRARITY.GOLD,
    [EQUIPS.DAPPER] = UGRARITY.PURPLE,
    [EQUIPS.DODGER] = UGRARITY.BLUE,
    [EQUIPS.MAXUSE] = UGRARITY.GREEN,
    [EQUIPS.MINING] = UGRARITY.WHITE,
    [EQUIPS.POISON] = UGRARITY.BLUE,
    [EQUIPS.PROOFR] = UGRARITY.WHITE,
    [EQUIPS.SPEEDR] = UGRARITY.PURPLE,
    [EQUIPS.SPLASH] = UGRARITY.GOLD,
    [EQUIPS.THORNS] = UGRARITY.GREEN,
    [EQUIPS.VAMPIR] = UGRARITY.PURPLE,
    [EQUIPS.WARMER] = UGRARITY.GREEN
}


local GEMS = {}
for k, v in pairs(EQUIPS) do
    GEMS[v.."_gem"] = {
        power = v,
        rarity = POWER_RARITY[v]
    }
end

return GEMS